### ISSUE TITLE
How to change colour of starts? I am getting black on my side.

### ISSUE THREAD

**Issue by gopalshimpi** [coryrylan/ngx-lite#6]
Hi...
Its very nice plugin. Could you plz tell how should we change the colour of stars.

**Comment by coryrylan** [comment]
I am still working on proper themes for all the ngxlite components for now you can add this to your global CSS file

```css
ngx-input-star-rating {
  --color-star-highlight: gold !important;
}
```
